# Generated by Django 5.1.2 on 2024-10-15 09:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Картинка')),
                ('image_mobile', models.ImageField(upload_to='portfolio', verbose_name='Картинка для мобилки')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('github_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на гитхаб проекта')),
                ('live_demo', models.TextField(blank=True, null=True, verbose_name='Ссылка на демо')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проект',
            },
        ),
        migrations.CreateModel(
            name='WorkExperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='work_experience', verbose_name='Иконка компаний')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компаний')),
                ('positions', models.CharField(max_length=255, verbose_name='Позиция на работе')),
                ('responsibility', ckeditor.fields.RichTextField(verbose_name='Обязанности по работе')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
    ]
