# Generated by Django 5.1.2 on 2024-10-16 06:52

import mainpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_portfolio_workexperiance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='icon',
            field=models.ImageField(upload_to=mainpage.models.derictory_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=mainpage.models.derictory_path, verbose_name='Картинка баннера'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='image_mobile',
            field=models.ImageField(null=True, upload_to=mainpage.models.derictory_path, verbose_name='Картинка баннера для мобилки'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume_file',
            field=models.FileField(upload_to=mainpage.models.derictory_path, verbose_name='Файл резюме'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=mainpage.models.derictory_path, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_mobile',
            field=models.ImageField(upload_to=mainpage.models.derictory_path, verbose_name='Картинка для мобилки'),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='icon',
            field=models.ImageField(upload_to=mainpage.models.derictory_path, verbose_name='Иконка компаний'),
        ),
    ]
